version: '3.8'
services:
  movies:
    image: rajagattem/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: rajagattem/train:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: rajagattem/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: rajagattem/payrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
